### ISSUE TITLE
Select non-continuous columns with read_features_from_text

### ISSUE THREAD

**Issue by jmmitc06** [shuzhao-li-lab/khipu#5]
Currently the read_features_from_text function only allows the selection of a continuous range of columns for intensity_cols e.g., 3 to 6. It would be useful to be able to specify a non-continuous set of columns for the intensities. 

This is very much a feature request and one that I can implement on my own, I'm just making the issue as a reminder to myself.

**Comment by shuzhao-li** [comment]
There is a function in JMS.io

**Comment by jmmitc06** [comment]
Those functions also seems to not allow non-continuous columns; however, refactoring them to handle this case would be considerable work for what was a "me" problem. I have handled this in the pipeline and I will close the issue since I don't think it is of general interest to implement this. Will revisit in the future if it arises.
